services:
  # Servicio Web Principal (Reflex + Webhook)
  - type: web
    name: nyme-app
    env: python
    rootDir: Nyme
    buildCommand: python build.py
    startCommand: export PATH=$PWD/node_bin/bin:$PATH && reflex run --env prod --single-port
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nyme-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: META_VERIFY_TOKEN
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: nyme-db
    plan: free
    databaseName: nyme_db
    user: nyme_user
